apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

  # NOTE: To use your secrets, encrypt them using kubeseal and save them.
resources:
- sealed-backend-secrets.yaml
- sealed-frontend-secrets.yaml
- ghcr-secret.yaml
- rbac.yaml
- cert-manager-issuer.yaml
- configmap.yaml
- game-server-headless.yaml
- http-server.yaml
- ws-server.yaml
- game-server.yaml
- sync-worker.yaml
- notification-worker.yaml
- matchmaker.yaml
- cdc.yaml
- web.yaml
- ingress.yaml
- grpc-ingress.yaml

# CI/CD (GitHub Actions) updates newTag to the latest build commit SHA
images:
- name: chess-cdc
  newName: ghcr.io/bhatvinay75/chess-cdc
  newTag: commit-35298ef
- name: chess-game-server
  newName: ghcr.io/bhatvinay75/chess-game-server
  newTag: commit-35298ef
- name: chess-http-server
  newName: ghcr.io/bhatvinay75/chess-http-server
  newTag: commit-7e2a6e0
- name: chess-matchmaker
  newName: ghcr.io/bhatvinay75/chess-matchmaker
  newTag: commit-35298ef
- name: chess-notification-worker
  newName: ghcr.io/bhatvinay75/chess-notification-worker
  newTag: commit-35298ef
- name: chess-sync-worker
  newName: ghcr.io/bhatvinay75/chess-sync-worker
  newTag: commit-35298ef
- name: chess-web
  newName: ghcr.io/bhatvinay75/chess-web
  newTag: commit-35298ef
- name: chess-ws-server
  newName: ghcr.io/bhatvinay75/chess-ws-server
  newTag: commit-35298ef
